# Generated by Django 4.2.7 on 2026-01-01 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_alter_deposit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='cryptocurrency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('USDC', 'USD Coin'), ('BNB', 'Binance Coin'), ('LTC', 'Litecoin'), ('XRP', 'Ripple'), ('ADA', 'Cardano')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='cryptocurrency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('USDC', 'USD Coin'), ('BNB', 'Binance Coin'), ('LTC', 'Litecoin'), ('XRP', 'Ripple'), ('ADA', 'Cardano')], max_length=10),
        ),
    ]
