# Generated by Django 4.2.7 on 2026-01-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0004_alter_cryptowallet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='cryptocurrency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT-ERC20', 'USDT (ERC-20 - Ethereum)'), ('USDT-TRC20', 'USDT (TRC-20 - Tron)'), ('USDT-BEP20', 'USDT (BEP-20 - BSC)'), ('USDC', 'USD Coin'), ('BNB', 'Binance Coin'), ('LTC', 'Litecoin'), ('XRP', 'Ripple'), ('ADA', 'Cardano')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='cryptocurrency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT-ERC20', 'USDT (ERC-20 - Ethereum)'), ('USDT-TRC20', 'USDT (TRC-20 - Tron)'), ('USDT-BEP20', 'USDT (BEP-20 - BSC)'), ('USDC', 'USD Coin'), ('BNB', 'Binance Coin'), ('LTC', 'Litecoin'), ('XRP', 'Ripple'), ('ADA', 'Cardano')], max_length=10),
        ),
    ]
