# Generated by Django 4.2.7 on 2026-01-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0005_alter_cryptowallet_cryptocurrency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='wallet_address',
            field=models.CharField(max_length=200),
        ),
    ]
