# Generated by Django 4.2.7 on 2026-01-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0006_alter_cryptowallet_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='currency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount entered in platform currency', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=8, help_text='Cryptocurrency amount', max_digits=15),
        ),
    ]
