# Generated by Django 4.2.7 on 2025-12-26 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('commission_earned', 'Commission Earned'), ('commission_paid', 'Commission Paid'), ('commission_cancelled', 'Commission Cancelled')], default='commission_earned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='referrals.referralcommission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Transaction',
                'verbose_name_plural': 'Commission Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
