# Generated by Django 4.2.7 on 2025-12-24 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='roi_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Enter ROI percentage (up to 99999.99%)', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999.99)]),
        ),
    ]
