# Generated by Django 4.2.7 on 2026-01-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_referral_code'),
        ('users', '0002_welcome_bonus_tracking'),
    ]

    operations = [
    ]
