# Generated by Django 4.2.7 on 2026-01-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20260101_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('NGN', 'Nigerian Naira'), ('ZAR', 'South African Rand'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('RUB', 'Russian Ruble'), ('AED', 'UAE Dirham')], max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate to USD', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('tr', 'Turkish'), ('nl', 'Dutch'), ('pl', 'Polish'), ('ko', 'Korean')], max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(help_text='Language name in native script', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rtl', models.BooleanField(default=False, help_text='Right-to-left language (Arabic, Hebrew, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Preferred currency for display', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.currency'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Preferred language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.language'),
        ),
    ]
