# Generated by Django 4.2.7 on 2026-01-01 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_currency_language_customuser_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Tesla Investment Platform', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(help_text='Default currency for all users', on_delete=django.db.models.deletion.PROTECT, to='users.currency')),
                ('language', models.ForeignKey(help_text='Default language for all users', on_delete=django.db.models.deletion.PROTECT, to='users.language')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
